### ISSUE TITLE
Export stuck

### ISSUE THREAD

**Issue by Iam-Muslim** [rebinf/QuranVideoMaker#31] opened 2023-08-21 22:40 UTC
Exporting stucks when exporting a long surah in a high resolution 
you can try maybe 4k and more than 1 hour surah to test this

**Comment by rebinf** [comment] 2023-08-31 19:57
As mentioned before, higher quality and longer length videos require a lot of RAM, you've very likely ran out of RAM while exporting.

**Comment by Iam-Muslim** [comment] 2023-09-01 08:57
yea i know the problem but we need to finnd a fix for that  😂 ❤️

**Comment by Dgriffin88** [comment] 2023-09-10 21:18
How do I find it

**Comment by rebinf** [comment] 2024-02-25 21:24
may be duplicate of #39 please try the latest update, if any problems, create another issue.

**Closed by rebinf** 2024-02-25 21:24 UTC
