### ISSUE TITLE
Exporting Bugs

### ISSUE THREAD

**Issue by redaamrmahmoud** [rebinf/QuranVideoMaker#5] opened 2023-06-24 00:16 UTC
Al slamo alaikom my brother , 
During Exporting any quality of video even if it was low , all of my pc resources are being used
My ram is 8 gb and it is used 100% 
My cpu is core i5 11th and it is used 100%
while the gpu is not used completely 

It should use the gpu instead of cpu during exporting

Thank you for this work , may allah reward you in afterlife <3

**Comment by rebinf** [comment] 2023-06-24 20:29
Wa Alaykum salam,

In general, the performance of the app is not great, it uses several external libraries in a "hacky way" to preview and export the videos.

I'm currently rewriting some of the code, once that's done, dealing with performance issues would be next.

Thank you for your kind words, you too.

**Comment by redaamrmahmoud** [comment] 2023-07-17 07:53
Alslamo alaikom my brother <3 ,
related to exporting 
most of time , exporting is stuck at half and it stops using the resources from my pc . 
i can appear in long recites more than 2 minutes

![image](https://github.com/rebinf/QuranVideoMaker/assets/98652126/aed82a19-9e3b-4942-b936-ca113e4d749e)

**Comment by rebinf** [comment] 2023-07-19 18:46
You're not bothering me at all 🙂

Thank you for reporting this issue and looking up solutions.

It is very likely it's running out of RAM, lower resolution videos take up less memory, that's probably why exporting the same poject works when lowering the resolution.

InShaAllah I will look into this and have a look at the suggested repos this weekend.

JazakAllahu Khayran

**Comment by rebinf** [comment] 2023-07-29 03:50
After some investigation, it seems like there was a massive memory leak caused by skiasharp.
Also further memory usage by using opencv to create the initial video.
For now garbage is collected during export several times, it feels very hacky but seems to be working.

The memory usage for a roughly 30 seconds of 4K video was about 40GB!
Now this is back down to about 7GB.
I've tested a similar video with kdenlive the memory usage was about 6GB.
So memory usage by QuranVideoMaker now seems acceptable.
As for the CPU, it is fully utilized, saw similar behavior with kdenlive.

For now I'm closing this issue.

**Closed by rebinf** 2023-07-29 03:50 UTC

**Comment by redaamrmahmoud** [comment] 2023-07-29 12:57
Thank you my brother , That was fixed 
The following link has 21 font for the great quran where you can use them . 
[https://easyupload.io/hbepjc](url)

Note that link expires after 30 days
Also , you can check ffmpeg latest release it has only one .exe instead of those all .dlls

may Allah bless you , Insha'a I will finish some work and start contributing with you <3

**Comment by rebinf** [comment] 2023-07-29 19:53
Thank you,

Thanks for the fonts, however I don't use file sharing websites, for various reasons, is there a reputable website where I can get the fonts?

That version of mpeg is much bigger is much bigger:

![Screenshot 2023-07-29 204958](https://github.com/rebinf/QuranVideoMaker/assets/16520022/fbc8d32f-7864-4d98-aeef-6d9128ee08f1)
![Screenshot 2023-07-29 205057](https://github.com/rebinf/QuranVideoMaker/assets/16520022/a07af3b7-2847-4956-b823-c4a9b5472f66)

Wa iyakum, a pull request is always welcome :)

**Comment by redaamrmahmoud** [comment] 2023-07-29 20:13
Thank you my brother for replying , 
yes you are right, it is much bigger .I didn't take size in consideration 
This link has 21 fonts but after testing it had 7 fonts only which worked well
The site is in arabic , insha'a Allah I'll search some other fonts after some time.
 
https://fonts.qurancomplex.gov.sa/

**Comment by rebinf** [comment] 2023-07-30 01:42
Thanks for the link, I've checked it out, I don't see any other better fonts than the uthmani script font.
Custom fonts can be put in Fonts folder in the app directory.
JazakAllahu Khayran
